// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onAutomaticoChange();

CloudTemperatureSensor temp;
CloudPercentage humedadSuelo;
CloudPercentage velFan1;
CloudPercentage velFan2;
CloudRelativeHumidity humedad;
bool automatico;

void initProperties(){

  ArduinoCloud.addProperty(temp, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humedadSuelo, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(velFan1, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(velFan2, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(humedad, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(automatico, READWRITE, ON_CHANGE, onAutomaticoChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
